controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

article_list:
    path: articles
    controller: App\Controller\Front\ArticleController::articleList

show_article:
    path: article/{id}
    controller: App\Controller\Front\ArticleController::showArticle

front_search:
    path: search
    controller: App\Controller\Front\ArticleController::frontSearch

admin_article_list:
    path: admin/articles
    controller: App\Controller\Admin\AdminArticleController::adminArticleList

admin_show_article:
    path: admin/article/{id}
    controller: App\Controller\Admin\AdminArticleController::adminShowArticle

admin_create_article:
    path: admin/create/article
    controller: App\Controller\Admin\AdminArticleController::adminArticleCreate

admin_update_article:
    path: admin/update/article
    controller: App\Controller\Admin\AdminArticleController::adminArticleUpdate

admin_delete_article:
    path: admin/delete/article
    controller: App\Controller\Admin\AdminArticleController::adminArticleDelete

category_list:
    path: categories
    controller: App\Controller\Admin\FrontCategoryController::categoryList

show_category:
    path: category/{id}
    controller: App\Controller\Admin\FrontCategoryController::showCategory

admin_category_list:
    path: admin/categories
    controller: App\Controller\Admin\AdminCategoryController::adminCategoryList

admin_show_category:
    path: admin/category/{id}
    controller: App\Controller\Admin\AdminCategoryController::adminShowCategory

admin_create_category:
    path: admin/create/category
    controller: App\Controller\Admin\AdminCategoryController::adminCreateCategory

admin_update_category:
    path: admin/update/category
    controller: App\Controller\Admin\AdminCategoryController::adminUpdateCategory

admin_delete_category:
    path: admin/delete/category
    controller: App\Controller\Admin\AdminCategoryController::adminDeleteCategory

writer_list:
    path: writers
    controller: App\Controller\Front\WriterController::writerList

show_writer:
    path: writer/{id}
    controller: App\Controller\Front\WriterController::showWriter

admin_writer_list:
    path: admin/writers
    controller: App\Controller\Admin\AdminWriterController::adminWriterList

admin_show_writer:
    path: admin/writer/{id}
    controller: App\Controller\Admin\AdminWriterController::adminShowWriter

admin_create_writer:
    path: admin/create/writer
    controller: App\Controller\Admin\AdminWriterController::adminCreateWriter

admin_update_writer:
    path: admin/update/writer
    controller: App\Controller\Admin\AdminWriterController::adminUpdateWriter

admin_delete_writer:
    path: admin/delete/writer
    controller: App\Controller\Admin\AdminWriterController::adminDeleteWriter

admin_search:
    path: admin/search
    controller: App\Controller\Admin\AdminWriterController::adminSearch

admin_image_list:
    path: admin/images
    controller: App\Controller\Admin\AdminImageController::adminImageList

admin_show_image:
    path: admin/image/{id}
    controller: App\Controller\Admin\AdminImageController::adminShowImage

admin_create_image:
    path: admin/create/image
    controller: App\Controller\Admin\AdminImageController::adminCreateImage

admin_update_image:
    path: admin/update/image
    controller: App\Controller\Admin\AdminImageController::adminUpdateImage

admin_delete_image:
    path: admin/delete/image
    controller: App\Controller\Admin\AdminImageController::adminDeleteImage

contact:
    path: contact
    controller: App\Controller\Front\MessageController::contact

message:
    path: message
    controller: App\Controller\Front\MessageController::message